<?php

namespace SimpleSAML\Test\Module\oidc\Services;

use SimpleSAML\Module\oidc\Services\LogoutTokenBuilder;
use PHPUnit\Framework\TestCase;

/**
 * @covers \SimpleSAML\Module\oidc\Services\LogoutTokenBuilder
 */
class LogoutTokenBuilderTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIncomplete(): void
    {
        $this->markTestIncomplete();
    }
}
